#
###################################
# Site wide configuration
####################################
#
title: Leonids
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jackie Trenh
  avatar: ![me](https://media-exp1.licdn.com/dms/image/C5603AQFhQeRt5yJaEQ/profile-displayphoto-shrink_200_200/0?e=1586995200&v=beta&t=gh5tnC2SUgMCW20o5CCLKryajDqF838PtMzYjUPSIdI)
  job: "Help Desk Specialist"
  bio: "this my site now.."
  email: mailto:jackietrenh@gmail.com
  disqus-shortname:
  twitter: jackietrenh
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jt96
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jackietrenh
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
